# Generated by Django 6.0.4 on 2026-04-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField()),
                ('body', models.CharField()),
            ],
        ),
    ]
