# Generated by Django 6.0.4 on 2026-04-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
